### ISSUE TITLE
environment.yml file 

### ISSUE THREAD

**Issue by anshudaur** [vadimkantorov/mask2cad_pytorch#1]
Hello vadim ,

First of all thank you very much for sharing your code for mask2cad paper.

Second, i am trying to train it on pix3d dataset and running into runtime error :

Traceback (most recent call last):
  File "train.py", line 291, in <module>
    main(args)
  File "train.py", line 153, in main
    val_dataset_as_coco = val_dataset.as_coco_dataset()
  File "/home/anshu/mask2cad_pytorch/pix3d.py", line 92, in as_coco_dataset
    annotations = [dict(
  File "/home/anshu/mask2cad_pytorch/pix3d.py", line 99, in <listcomp>
    segmentation = mask_to_rle(torchvision.io.read_image(os.path.join(self.root, m['mask']))[0] == 255),
  File "/home/anshu/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/torchvision/io/image.py", line 230, in read_image
    return decode_image(data)
  File "/home/anshu/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/torchvision/io/image.py", line 211, in decode_image
    output = torch.ops.image.decode_image(input)
RuntimeError: Non RGB images are not supported.

I think it can be easily fixed if i have the environment/configuration file w.r.t to the code.

It would be great help if you can share it.

Thank
Anshu

**Comment by tb2-sy** [comment]
"FileNotFoundError: [Errno 2] No such file or directory: 'data/common/pix3d/pix3d.json'",Hello,Do you have this
file?

**Comment by tb2-sy** [comment]
> Hello vadim ,
> 
> First of all thank you very much for sharing your code for mask2cad paper.
> 
> Second, i am trying to train it on pic3d dataset and running into runtime error :
> 
> Traceback (most recent call last): File "train.py", line 291, in main(args) File "train.py", line 153, in main val_dataset_as_coco = val_dataset.as_coco_dataset() File "/home/anshu/mask2cad_pytorch/pix3d.py", line 92, in as_coco_dataset annotations = [dict( File "/home/anshu/mask2cad_pytorch/pix3d.py", line 99, in segmentation = mask_to_rle(torchvision.io.read_image(os.path.join(self.root, m['mask']))[0] == 255), File "/home/anshu/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/torchvision/io/image.py", line 230, in read_image return decode_image(data) File "/home/anshu/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/torchvision/io/image.py", line 211, in decode_image output = torch.ops.image.decode_image(input) RuntimeError: Non RGB images are not supported.
> 
> I think it can be easily fixed if i alos have the environment/configuration file w.r.t to the code.
> 
> It would be great help if you can share it.
> 
> Thank Anshu

Did you run the code successfully? I tried a lot, but now I still have no success. I almost gave up......

**Comment by vadimkantorov** [comment]
The project is incomplete, so problems are expected. You will need to debug it a lot to make it work
